baseURL = "https://rajeshbhola.github.io/rajesh-bhola/"
languageCode = "en-us"
title = "Rajesh Bhola"
# theme = ""
copyright = "© 2025 Rajesh Bhola ... All rights reserved."

[params]
  author = "Rajesh Bhola"
  description = "Discover our most recent articles and insights"
  
  # Google Analytics
  googleAnalytics = "G-XXXXXXXXXX"  # Replace with your GA4 tracking ID
  
  # Google AdSense
  googleAdSenseID = "ca-pub-XXXXXXXXXX"  # Replace with your AdSense Publisher ID
  
  # Affiliate Settings
  [params.affiliate]
    amazon = "your-amazon-tag"  # Replace with your Amazon Associates tag
    disclaimer = "This site contains affiliate links. We may earn a commission if you click on a link and make a purchase."
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params.seo]
  keywords = ["blog", "technology", "web development", "static site generator"]
  ogImage = "/images/og-image.jpg"
  twitterHandle = "@rajeshbhola"

[pagination]
pagerSize = 9